//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rx3Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rx3Tools.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip boot flow.
        /// </summary>
        public static string TEXT_BOOT_FLOW {
            get {
                return ResourceManager.GetString("TEXT_BOOT_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string TEXT_BROWSE {
            get {
                return ResourceManager.GetString("TEXT_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug console.
        /// </summary>
        public static string TEXT_DEBUG_CONSOLE {
            get {
                return ResourceManager.GetString("TEXT_DEBUG_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Not a FIFA 16 folder.
        /// </summary>
        public static string TEXT_ERROR_WRONG_FOLDER {
            get {
                return ResourceManager.GetString("TEXT_ERROR_WRONG_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TEXT_EXIT {
            get {
                return ResourceManager.GetString("TEXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string TEXT_INSTALL {
            get {
                return ResourceManager.GetString("TEXT_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Loader successfully installed.
        /// </summary>
        public static string TEXT_INSTALLED {
            get {
                return ResourceManager.GetString("TEXT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string TEXT_MESSAGE {
            get {
                return ResourceManager.GetString("TEXT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Loader can&apos;t be installed on this game version.
        ///
        ///Supported game versions are:
        ///
        ///    FIFA 16 16.0.2904053 (exe size - 117 906 200 bytes)
        ///    FIFA 16 16.0.2904053 (exe size - 117 868 544 bytes).
        /// </summary>
        public static string TEXT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TEXT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FIFA 16 directory.
        /// </summary>
        public static string TEXT_SELECT {
            get {
                return ResourceManager.GetString("TEXT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string TEXT_UNINSTALL {
            get {
                return ResourceManager.GetString("TEXT_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Loader successfully uninstalled.
        /// </summary>
        public static string TEXT_UNINSTALLED {
            get {
                return ResourceManager.GetString("TEXT_UNINSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable windowed mode.
        /// </summary>
        public static string TEXT_WINDOWED_MODE {
            get {
                return ResourceManager.GetString("TEXT_WINDOWED_MODE", resourceCulture);
            }
        }
    }
}
